steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://irish-narr-build-dependencies/apache-jena-3.15.0.tar.gz', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/irish-narr', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--volume', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/irish-narr', 'bash']
    env: ['IRISH_GEN_HOME=/workspace']

images:
  - 'gcr.io/$PROJECT_ID/irish-narr'
