steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/irish-narr', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/irish-narr', 'bash']
        
images:
  - 'gcr.io/$PROJECT_ID/irish-narr'
